---
ID: "62907b2b-9c0a-4a2a-9758-7b29b22ed91b"
Parent: "3a1e055a-9933-4f01-bfb1-e123f221d0cb"
Template: "3a1e055a-9933-4f01-bfb1-e123f221d0cb"
Path: /sitecore/templates/Feature/Habitat Home/Components/NavigationBase/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "03f0061a-309d-4732-a722-2f2a1488ac60"
      Hint: NavigationTitle
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190423T105303Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "54e7adc3-d2eb-4ed4-8a3a-3a2903d40036"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190613T142103Z
