---
ID: "c3bf3101-b0fe-44a4-bcd2-70f7a76cc437"
Parent: "55deeeda-d3ee-47c6-ad8d-1b61e5e94baa"
Template: "55deeeda-d3ee-47c6-ad8d-1b61e5e94baa"
Path: /sitecore/templates/Feature/Habitat Home/Components/Carousel/Carousel/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{DC33F27E-0B5B-416E-A8DD-03F5F9F22A27}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190121T192826Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ed676385-d2c1-48b7-9de8-0cd6cfa69712"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190613T142103Z
